services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  kafka:
    image: apache/kafka:3.7.0
    container_name: gye_kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,INTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
  spark-master:
    image: apache/spark:3.5.1
    container_name: gye_spark_master
    volumes:
      - ../:/workspace
      - ./jars:/opt/spark/user-jars
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: >
      bash -lc 'cp /opt/spark/user-jars/*.jar /opt/spark/jars/ 2>/dev/null || true;
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master'

  spark-worker:
    image: apache/spark:3.5.1
    container_name: gye_spark_worker
    volumes:
      - ../:/workspace
      - ./jars:/opt/spark/user-jars
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_NO_DAEMONIZE=true
    command: >
      bash -lc 'cp /opt/spark/user-jars/*.jar /opt/spark/jars/ 2>/dev/null || true;
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077'

volumes:
  namenode_data:
  hadoop_datanode:
  kafka_data:
